- name: variables from files
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name: get varibales from file
    ansible.builtin.debug:
      msg: "Hi learning {{COURSE}} from Trainer {{TRAINER}}, Duration is {{DURATION}}."
  